"""empty message

Revision ID: 11759effec7f
Revises: 2f31bceb883e
Create Date: 2022-08-17 18:30:31.771331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11759effec7f'
down_revision = '2f31bceb883e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('gender', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('mobile', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['lastname'])
    op.create_unique_constraint(None, 'user', ['age'])
    op.create_unique_constraint(None, 'user', ['gender'])
    op.create_unique_constraint(None, 'user', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
