"""empty message

Revision ID: 6b0ef2d65925
Revises: 13c887433907
Create Date: 2022-08-20 08:04:16.762017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0ef2d65925'
down_revision = '13c887433907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_constraint('user_age_key', 'user', type_='unique')
    op.drop_constraint('user_gender_key', 'user', type_='unique')
    op.drop_constraint('user_lastname_key', 'user', type_='unique')
    op.drop_constraint('user_mobile_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'address')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_mobile_key', 'user', ['mobile'])
    op.create_unique_constraint('user_lastname_key', 'user', ['lastname'])
    op.create_unique_constraint('user_gender_key', 'user', ['gender'])
    op.create_unique_constraint('user_age_key', 'user', ['age'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
