"""empty message

Revision ID: a40e66eab4f2
Revises: fa19ba9c8acc
Create Date: 2022-08-19 18:58:27.562177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40e66eab4f2'
down_revision = 'fa19ba9c8acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'date',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('activities', 'latitude',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
    op.alter_column('activities', 'longitude',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
    op.alter_column('activities', 'time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_constraint('activities_category_key', 'activities', type_='unique')
    op.drop_constraint('activities_city_key', 'activities', type_='unique')
    op.drop_constraint('activities_date_key', 'activities', type_='unique')
    op.drop_constraint('activities_latitude_key', 'activities', type_='unique')
    op.drop_constraint('activities_location_key', 'activities', type_='unique')
    op.drop_constraint('activities_longitude_key', 'activities', type_='unique')
    op.drop_constraint('activities_name_key', 'activities', type_='unique')
    op.drop_constraint('activities_players_key', 'activities', type_='unique')
    op.drop_constraint('activities_time_key', 'activities', type_='unique')
    op.drop_constraint('activities_weather_key', 'activities', type_='unique')
    op.drop_column('activities', 'weather')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('weather', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('activities_weather_key', 'activities', ['weather'])
    op.create_unique_constraint('activities_time_key', 'activities', ['time'])
    op.create_unique_constraint('activities_players_key', 'activities', ['players'])
    op.create_unique_constraint('activities_name_key', 'activities', ['name'])
    op.create_unique_constraint('activities_longitude_key', 'activities', ['longitude'])
    op.create_unique_constraint('activities_location_key', 'activities', ['location'])
    op.create_unique_constraint('activities_latitude_key', 'activities', ['latitude'])
    op.create_unique_constraint('activities_date_key', 'activities', ['date'])
    op.create_unique_constraint('activities_city_key', 'activities', ['city'])
    op.create_unique_constraint('activities_category_key', 'activities', ['category'])
    op.alter_column('activities', 'time',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('activities', 'longitude',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('activities', 'latitude',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('activities', 'date',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
