"""empty message

Revision ID: fa19ba9c8acc
Revises: 11759effec7f
Create Date: 2022-08-17 18:33:46.496031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa19ba9c8acc'
down_revision = '11759effec7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('weather', sa.String(length=120), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('longitude'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('players'),
    sa.UniqueConstraint('time'),
    sa.UniqueConstraint('weather')
    )
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'age',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('activities')
    # ### end Alembic commands ###
